### ISSUE TITLE
Clicking the buttons in 1.0.2 does nothing

### ISSUE THREAD

**Issue by Kordonme** [Jyben/csgo-mm-server-picker#1]
There's a little GIF [here](https://i.imgur.com/GxcXCDV.gifv).

**Comment by ArsenicBismuth** [comment]
Got similar problems, so I tried to check it myself.

Turns out every single ping done by the program to the host IP addresses are timed out, Hence everything seems "unresponsive". I tried to ping it myself using CMD and those IPs are okay, so it's not like they're outdated.

**Comment by ArsenicBismuth** [comment]
Okay, find the core problem. The ping library used, `ping-lite`, is outdated (a year ago) and it's failing to build: https://travis-ci.org/ben-bradley/ping-lite

**Comment by ArsenicBismuth** [comment]
Found the core problem. The ping library used, `ping-lite`, is outdated (a year ago) and it's failing to build: https://travis-ci.org/ben-bradley/ping-lite

**Comment by ArsenicBismuth** [comment]
Found the core problem. The ping library used, `ping-lite`, is outdated (a year ago) and it's failing to build: https://travis-ci.org/ben-bradley/ping-lite

Even testing its test program directly would give a "null" `ms` response.

**Comment by ArsenicBismuth** [comment]
Found the core problem. The ping library used, `ping-lite`, is outdated (a year ago) and it's failing to build: https://travis-ci.org/ben-bradley/ping-lite

Even using its test program directly would give a "null" `ms` response.

**Comment by ArsenicBismuth** [comment]
Found the solution, you must modify the ping-lite module.

From this:
`this._regmatch = /[><=]([0-9.]+?) ms/;`
To this:
`this._regmatch = /[><=]([0-9.]+?)ms/;`

**Comment by Jyben** [comment]
I understand now why I was unable to reproduce this issue, it's because my Windows language is in french then the stdout return the time with a whitespace between "=" and the time... In english there is no whitespace. 
So I added the keyword \s* to ignore whitespaces : `this._regmatch = /[><=]([0-9.]+?)\s*ms/;`

**Comment by Jyben** [comment]
Thank you @ArsenicBismuth for your investigation and your time !

**Comment by ArsenicBismuth** [comment]
> Windows language is in french

Ah, I figured that might be the case, since you're French (such as using space before question & exclamation mark). Then I remembered that ping-lite is developed by another guy, so I didn't think too much of it.

Likewise, thanks for developing this. You need to put this somewhere more accessible tho, it's way better than those found in Google. Found this by sheer luck since search engine hardly pick it up (no readme = no metadata).
