### ISSUE TITLE
what is this and how do i fix

### ISSUE THREAD

**Issue by wellthisucks** [Jyben/csgo-mm-server-picker#16]
![hja](https://user-images.githubusercontent.com/66989525/84737005-08174a80-af75-11ea-914a-6ad64c330944.PNG)
![hjo](https://user-images.githubusercontent.com/66989525/84737006-08afe100-af75-11ea-9274-8e755730f59a.PNG)

**Comment by Jyben** [comment]
Hello, can you please send me the log file at
C:\Users\Brendan\AppData\Local\Programs\csgo-mm-server-picker

**Comment by Jyben** [comment]
Nevermind, I have the issue too, I will fix that.

**Comment by wellthisucks** [comment]
ok cool

**Comment by Jyben** [comment]
Fixed by commit a0d238c1dac57bb3a0452de4f2e23fa1a7ccb407

If you can't get the automatic update while you start the app in 1.1.1, please uninstall properly with the uninstaller before to install the new version (1.1.2)
The uninstaller is in this folder (replace username by your Windows username :
C:\Users\username\AppData\Local\Programs\csgo-mm-server-picker
