### ISSUE TITLE
Fix if you can't access internet after using the Program (Windows).

### ISSUE THREAD

**Issue by ArsenicBismuth** [Jyben/csgo-mm-server-picker#4]
Basically, the program adds new rules inside the Windows Defender Firewall, which can be accessed from:

1. Start > Search "Windows Defender Firewall".
2. Advanced Settings.
3. Outbound Rules.

After activating this app, you'll see several new rules added there. In case your internet is totally disabled all of a sudden, remove some of the rules called "csgo-mm-server-picker". As you can see there, it restricts any kind of connection (dunno why).

The basic mechanism should be written in the repository description itself, so that user can find their way in to fix problems if the program can't. But yeah, it's a personal project, can't expect much (already good as is).

**Comment by Jyben** [comment]
Thank you for your report. 
The fact that it restricts your connection is weird because the app only blocks Valve's IP addresses, found [here](https://raw.githubusercontent.com/SteamDatabase/SteamTracking/master/Random/NetworkDatagramConfig.json).

About the multiple rules in the firewall, I will fix that because there should only be one.

I will also add a description of how the application works in the Readme file.

**Comment by ArsenicBismuth** [comment]
The problem runs deeper, it's all rooted on the broken ping functionality.

You can check the older issue about this, I've found the solution:
https://github.com/Jyben/csgo-mm-server-picker/issues/1

I've also started a pull request for a quick fix.
