### ISSUE TITLE
Unable to access to the internet

### ISSUE THREAD

**Issue by stigchen2333** [Jyben/csgo-mm-server-picker#40]
Hi Jyben, Hope you are well.
After the software updates itself to 113 version, my internet stopped working. For some reasons Windows refuses to connect to the DHCP server. WIFI can be connected but no internet. As you are familiar with the design of this application, any chance you can advice me what might be the problem?
Thanks.
David

**Comment by Jyben** [comment]
Hi, the app only adds some rules in your Windows Firewall to block Valve relay servers, with this line : 

https://github.com/Jyben/csgo-mm-server-picker/blob/784e38c08c441c7b22830f3c3230836915ec7970/app/main-process/firewall.js#L20

This is the only line that modify your windows settings, so I'm not sure that your problem is the app. The only thing you can do is to reset the configuration by cliking the reset button in the app, or, to go in your Firewall settings and delete manually the rule named "csgo-mm-server-picker".

**Comment by stigchen2333** [comment]
Thanks for the reply. You are correct. This problem is solved by resetting the firewall. 
Cheers.
